# Generated by Django 4.1.1 on 2022-10-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Officer',
        ),
        migrations.RenameModel(
            old_name='StaffNotification',
            new_name='OfficerNotification',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='staffID',
            new_name='officerID',
        ),
        migrations.RenameField(
            model_name='officernotification',
            old_name='staff_id',
            new_name='officer_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'OFFICER'), (3, 'TEACHER'), (4, 'STUDENT')], default=1, max_length=50),
        ),
    ]
