# Generated by Django 4.1.1 on 2022-10-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_staff_officer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course_id',
            new_name='department_id',
        ),
    ]
