# Generated by Django 4.1.1 on 2022-10-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='department_id',
            new_name='department_name',
        ),
    ]
